### ISSUE TITLE
EPIC: Introduce Concept and Handling of Existing Derivatives

### ISSUE THREAD

**Issue by jeremyf** [samvera-labs/bulkrax#760]
## Problem Statement

As people leverage Bulkrax to migrate from one solution to Hyrax, we are noting that many of them have existing derivatives that they would like to bring along.

For example, a curated thumbnail of a video; an already generated HOCR file, etc.

At present (<2023-03-16 Thu>), Bulkrax and Hyrax has no consideration for importing/leveraging existing derivatives.

This issue outlines a design overview and a draft task breakdown to address this problem statement.

## Design Overview

Add the following CSV columns to a `FileSet` entry:

-   **derivative\_thumbnail (arity 1):** When given this will be used as the thumbnail for the FileSet.
-   **derivative\_translation (arity many):** When given this will be added as translations for the FileSet.
-   **deriviatve\_hocr (arity 1):** When given this will be used as the HOCR file.

We likely will want to consider arbitrary suffixes.  We would store these suffixes on a child database table of the `Bulkrax::Entry` (e.g. `bulkrax_entry_derivatives`).  At present, we’re working with URLs, but may also want to consider path relative files as well (e.g. from the importer’s file).

Then during the `CreateDerivativesJob`, we would leverage a `DerivativeFileLocator` service.  The interface of a locator is:

-   Given a `FileSet` and a `derivative type` (e.g. thumbnail, hocr, translation)
-   Return (or yield) that `derivative file(s)`

For each `derivative type` we would register a set of strategies for locating the file.  The `DerivativeFileLocator` would try each strategy, breaking after the first successful locating.

One strategy would be: For the given `derivative type` check the `bulkrax_entry_derivatives` for a path/URL.  When it exists, download the file at the given URL and return that as the `derivative file`.

Another strategy would be to take the original file of the `FileSet` and generate the derivative.

## Task Breakdown [Draft]

-   [ ] Create `Bulkrax::EntryDerivative` that belongs to `Bulkrax::Entry`.  The fields would be: `entry_id` (as a foreign key), `derivative_type`, and `path`.
-   [ ] Adjust parser/entry to capture the `derivative_*` fields.  To consider: parser mappings with a `:from` directive.
-   [ ] Create the `Hyrax::DerivativeFileLocator`; this will likely live in Bulkrax but is generally applicable.
    -   Its public API method is `.call(file_set:, derivative_type:)` which returns an array of file name paths.  *Would it make sense instead to yield the paths?  In this way we’d yield once for each file.*
    -   Having a clear API for the file locator would allow for other gems (e.g. `IiifPrint`) to implement the simple locator concepts.
-   [ ] Write a replacement for `Hyrax::FileSetDerivativesService` that leverages the `Hyrax::DerivativeFileLocator` interface.  This has a high probability of spiraling into a large refactor as possibly dives into the implementation details of the `Hydra::Derivatives` gem.

The [`Hydra::Derivatives::PdfDerivatives.create` method](https://github.com/samvera/hyrax/blob/76176286b817c869a80b922ccacc6fecea3827e2/app/services/hyrax/file_set_derivatives_service.rb#L69-L79) below is part of the current `Hyrax::FileSetDerivativesService`; it is responsible for taking the given original filename and then attaching the thumbnail at `derivative_url('thumbnail')` location.  In other words the `Hydra::Derivative::PdfDerivatives.create` needs to be able to leverage the `Hyrax::DerivativeFileLocator`.

```ruby
Hydra::Derivatives::PdfDerivatives.create(
  filename,
  outputs: [{
              label: :thumbnail,
              format: 'jpg',
              size: '338x493',
              url: derivative_url('thumbnail'),
              layer: 0
            }])
```

**Comment by ShanaLMoore** [comment]
Once upon a time I heard (from Crystal) that Tamsin may already be working out a solution for this (in Bulkrax I believe). I'm going to see if I can track it down if, for nothing else, comparison's sake. Best case is maybe its' something we can leverage. 

I remember Crystal's attempts to get an update but I don't recall if they ever responded.

**Comment by jeremyf** [comment]
In discussion, we have the concept of locator and applicator, which the Hydra::Derivatives current mashes together as a single concept.
